repos:
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        args: [--line-length, "88"]

  # - repo: https://github.com/asottile/blacken-docs
  #   rev: v1.12.0
  #   hooks:
  #     - id: blacken-docs

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args:
          [
            --ignore,
            "E203,E501,W503",
            "--max-line-length",
            "100",
            "--per-file-ignores",
            "*/__init__.py:F401",
          ]
        additional_dependencies: [flake8-bugbear]

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--profile, "black", "--line-length", "88"]

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v0.930
  #   hooks:
  #     - id: mypy
  #       args: [--ignore-missing-imports]
  #       additional_dependencies: [types-freezegun]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace
