[tool.poetry]
name = "atcoder-util-problem"
version = "0.1.0"
description = ""
authors = ["edge2992 <torune.summer@gmail.com>"]
readme = "README.md"
packages = [{include = "atcoder_util_problem"}]

[tool.poetry.dependencies]
python = "^3.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
